version: '3.8'

services:
  database:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      POSTGRES_DB: logistics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepass
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      DB_HOST: database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
  